### ISSUE TITLE
Support for anonymous users

### ISSUE THREAD

**Issue by roryf** [launchdarkly/react-native-client-sdk#100]
**Is your feature request related to a problem? Please describe.**
I would like to use the SDK for anonymous users, i.e. pre-registration in our app.

**Describe the solution you'd like**
Make `user` an optional parameter in `LDClient#configure`. Even if i ignore typescript warnings, the [`LaunchdarklyReactNativeClient#internalConfigure`](https://github.com/launchdarkly/react-native-client-sdk/blob/master/ios/LaunchdarklyReactNativeClient.swift#L39) function requires a user object to configure the native iOS client.

**Describe alternatives you've considered**
As far as I can tell, the only way around this currently is to generate my own `key` and pass `{ key: myGeneratedRandomKey, anonymous: true }` to `configure`.

**Additional context**
The React client clearly [defaults to anonymous user](https://github.com/launchdarkly/react-client-sdk/blob/master/src/initLDClient.ts#L20) without specifying a key, and the initial `user` parameter is optional in the underlying [LDClient iOS SDK](https://github.com/launchdarkly/ios-client-sdk/blob/v5/LaunchDarkly/LaunchDarkly/LDClient.swift#L818)

**Comment by roryf** [comment]
I have tried passing `{ anonymous: true }` and the promise from `configure` is not resolved _or_ rejected. (this is probably a separate bug)

**Comment by bwoskow-ld** [comment]
Hi @roryf,

Our React Native SDK _does_ work for anonymous users. However, at present you'll need to provide a user object with both a defined `key` attribute and `anonymous: true` as you noted in your workaround.

Our React Native SDK is written as a wrapper around our native iOS and Android SDKs. While this improves our ability to develop and maintain the SDK more efficiently, it also means that from time to time we need to deal with inconsistencies between the native SDKs' behavior and APIs. As you pointed out, the [iOS SDK](https://github.com/launchdarkly/ios-client-sdk/blob/v5/LaunchDarkly/LaunchDarkly/LDClient.swift#L818) takes an optional `user` parameter -- however, the [Android SDK](https://launchdarkly.github.io/android-client-sdk/com/launchdarkly/sdk/android/LDClient.html#init-android.app.Application-com.launchdarkly.sdk.android.LDConfig-com.launchdarkly.sdk.LDUser-) _requires_ the `user` parameter when initializing. This is why the React Native SDK also requires that a user be provided at initialization.

You also linked to the [React SDK](https://github.com/launchdarkly/react-client-sdk/blob/master/src/initLDClient.ts#L20) as an example where the behavior differs. This is because of [a feature](https://docs.launchdarkly.com/sdk/features/user-config#anonymous-users-in-the-javascript-sdk) we built into our JavaScript SDK where the SDK can automatically generate unique keys for anonymous users. We haven't carried this feature over to any other SDKs (other than the React SDK which is implemented as a wrapper around the JS SDK, similar to the relationship between the React Native SDK and the native iOS/Android SDKs). I believe that _this_ is what your feature request is most about -- that you want the React Native SDK to automatically generate user keys when provided with a user of `{ anonymous: true }`, rather than actually making the `user` attribute optional.

Can you confirm that this is what you're after? In the time until this feature request is addressed, you'll need to generate user keys in your own application code when initializing the SDK.

As for your follow-up comment, this does sound like a separate bug that can be investigated. The promise should definitely either resolve or be rejected in all cases.

Cheers,
@bwoskow-ld

**Comment by roryf** [comment]
@bwoskow-ld thanks for the detailed explanation, makes sense.

> Can you confirm that this is what you're after?

Yes, passing `{ anonymous: true }` and having key generated by the SDK would work fine.

**Comment by bwoskow-ld** [comment]
Understood, thanks. I filed a feature request for this on our backlog. It isn't a high priority at the moment, though, so I do recommend in the meantime that you continue to generate the user key in your application code before passing in fully constructed user object.

_Filed internally as 130395._

**Comment by andrew-hm** [comment]
if you're using segment, their [library](https://github.com/segmentio/analytics-react-native) generates `anonymousId` well that comply with [Apple’s required privacy policies](https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/#unique-identifiers-in-ios), maintains compatibility, and also enables correct tracking in situations where multiple people use the same device, since the UUID can be regenerated.

**Comment by roryf** [comment]
@andrew-hm thanks, we are using Segment and it's presented another issue where the `anonymousId` we generate for LD does not match the events Segment is sending which prevents experiments from showing any conversions. So we need to change this to use the Segment `anonymousId` anyway, which kinda makes this request redundant in our use case!

**Comment by shaddeen** [comment]
Any idea where this feature sits in your roadmap?

**Comment by gwhelanLD** [comment]
Hi @shaddeen,

We've just released [5.1.1](https://github.com/launchdarkly/react-native-client-sdk/releases/tag/5.1.1) which should resolve this issue. The React Native SDK will automatically generate a key for for users when one is not provided and mark the user as anonymous as of this version. I'll close this issue now that we've added this support.

Hope this helps,
@gwhelanLD
