### ISSUE TITLE
Create a unique method to retrieve a variation

### ISSUE THREAD

**Issue by andreaSimonePorceddu** [launchdarkly/react-native-client-sdk#104]
**Is your feature request related to a problem? Please describe.**

Currently, the `react-native-client-sdk` doesn't provide a unique method to fetch a single flag variation. 
We need to know the flag type and use the related method to do it:
<img width="386" alt="Schermata 2021-12-16 alle 18 13 23" src="https://user-images.githubusercontent.com/55460313/146419778-9dce8f28-4827-45ad-862c-eb68931874a9.png">

[Here's the related documentation](https://docs.launchdarkly.com/sdk/features/evaluating#react-native)

This makes the operation very convoluted in case it is necessary to retrieve the value of a variation x of which we do not know the type.

**Describe the solution you'd like**
Create a unique method that allows retrieving a variation like in the JS SKD [Docs here](https://docs.launchdarkly.com/sdk/features/evaluating#javascript)

```typescript
const value = client.variation("your.feature.key", false);
```

**Comment by louis-launchdarkly** [comment]
Hello @andreaSimonePorceddu, thank you for the issue report. After an investigation, we found the iOS SDK currently does not have a generic LDValue interface like our other SDKs (e.g. Android SDK has that concept). We will need to enhance the iOS SDK first before we can tackle this issue. I will mark this as an enhancement.

Filed Internally as 135905

**Comment by yusinto** [comment]
The react-native SDK has been re-written and [released](https://github.com/launchdarkly/js-core/tree/main/packages/sdk/react-native). The new version v10 is purely in TypeScript and supports Expo. We recommend using the strongly typed variation [hooks](https://docs.launchdarkly.com/sdk/features/evaluating#react-native) because it does type checks and validation. However, the [useTypedVariation](https://launchdarkly.github.io/js-core/packages/sdk/react-native/docs/functions/useTypedVariation.html) hook can evaluate flags without specifying a type.

Please consider upgrading to that new version to fix this issue. Thank you for your patience.
