### ISSUE TITLE
[Feature Request] Support for Expo Config Plugins

### ISSUE THREAD

**Issue by leggomuhgreggo** [launchdarkly/react-native-client-sdk#110]
I am on a team that's fixin to start work on a cross-platform Expo app, intended to replace our three legacy clients. Wanted to inquire whether y'all would consider adding support for [Config Plugins](https://docs.expo.io/guides/config-plugins/), so this library can be used with the Expo Managed Workflow (i.e. without ejecting)

Thanks for your consideration!

## Feature Context

Over the past several months Expo has introduced features which enable apps to use external native modules, without ejecting Expo's managed workflow. 

The customizations to the iOS and Android code that are required by a given native module are automated, using an AST-based API that Expo provides through  "Config Plugins" feature.

These automations (called "mods") are executed during a new "Prebuild" phase, in which boilerplate ios and android directories are created — and then their respective files are altered, based on the instructions in a given modules config plugin. The end result is essentially the same as if you ejected and manually changed the ios/android files. 

Here's the [Expo blog post](https://blog.expo.io/introducing-expo-run-commands-835ae8da4813) announcing Config Plugins and the associated feature-set.

## Overview of Proposed Implementation

The process for creating a Config Plugin is detailed here:
https://docs.expo.io/guides/config-plugins/#creating-a-plugin

There are a few different "recipes" for how to implement — but the gist of it is:

- Create the `app.plugin.js` file, at the project root — which serves as a standard entrypoint where expo can resolve the plugin code. [ex: [`expo-camera`](https://github.com/expo/expo/blob/master/packages/expo-camera/app.plugin.js)]
- Export a function prefixed using "with" (eg `withFeature`) which accepts a `config` object that can be used, along with `@expo/config-plugins` methods, to implement mods for each platform's native code. [ex: [`withCamera`](https://github.com/expo/expo/blob/master/packages/expo-camera/plugin/src/withCamera.ts)]
- Add mods corresponding to the setup steps in your README.md
- Celebrate!

## Additional Question

Are there specific feature in the RN SDK, that aren't supported in the standard React SDK? I've been trying to parse the docs a little bit but it's not totally clear to me. Thanks!

**Comment by louis-launchdarkly** [comment]
Hello @leggomuhgreggo, thank you for the feature request! While we are currently focusing on fixing some of the issues reported for React Native, we will discuss this and give you an update afterward.

**Comment by leggomuhgreggo** [comment]
Thanks @louis-launchdarkly 

I wonder if, in the mean time, you might be able to offer clarification on the question:

> Are there specific feature in the RN SDK, that aren't supported in the standard React SDK? I've been trying to parse the docs a little bit but it's not totally clear to me.

🙏

**Comment by louis-launchdarkly** [comment]
Hello @leggomuhgreggo, that is a good question - based on the documentation [React Native](https://docs.launchdarkly.com/sdk/client-side/react/react-native) and [JavaScript for React](https://docs.launchdarkly.com/sdk/client-side/javascript), the key difference that is supported in React Native but not React are mobile specific features. The two that I know of are [Monitor SDK Status](https://docs.launchdarkly.com/sdk/features/monitoring#react-native) and [Offline Mode](https://docs.launchdarkly.com/sdk/features/offline-mode#react-native)

**Comment by yvan33** [comment]
@louis-launchdarkly - Any update on this? We also need this in my team.
Ejecting from the Expo managed workflow is not an easy move and not preferable for us.

**Comment by erisvaldojunior** [comment]
Any news on this?

**Comment by louis-launchdarkly** [comment]
Hello @yvan33 and @erisvaldojunior, thank you for checking. Unfortunately, we are not getting to this yet, and this is still an open enhancement request in the backlog. 

I should have asked earlier - is there anyone interested in making a contribution to implement this? Engineers who are familiar with the Expo will likely implement this better than us, who are not familiar with the Expo framework.

**Comment by ridafkih** [comment]
@louis-launchdarkly I got it

**Comment by mjphillips-sg** [comment]
The docs should be updated to reflect this, currently it says you can't use LaunchDarkly with Expo,  @louis-launchdarkly.

We're moving off Xamarin / MAUI to Expo, we'll do some testing and report back as well and hopefully confirm what @yvan33 said!

**Comment by yvan33** [comment]
@teesloane - Yes it worked out of the box using EAS to build the application (since it installs the native dependencies using Cocoapods).

For development, that also mean you need to build a custom [dev client](https://www.npmjs.com/package/expo-dev-client) instead of using Expo go.

**Comment by teesloane** [comment]
> @teesloane - Yes it worked out of the box using EAS to build the application (since it installs the native dependencies using Cocoapods).
> 
> For development, that also mean you need to build a custom [dev client](https://www.npmjs.com/package/expo-dev-client) instead of using Expo go.

Thanks @yvan33 , I'll give this a shot; I had missed `expo-dev-client` during my research. Cheers!

**Comment by YishaiGr** [comment]
@louis-launchdarkly can you please confirm if you guys are planning to support expo development builds, like the developers here are mentioning that its working?
If so I would appreciate if you guys can update your docs and mention it, thanks.

**Comment by louis-launchdarkly** [comment]
Hello @YishaiGr, thank you for the question. To be accurate, with the current project, it seems that the community figures out a way to make Expo work, and there is no plan to intentionally break things. However, there is no Expo internal testing right now either, we only have testing to ensure the RN SDK still works correctly for Android and iOS.

There is a plan to work on a mostly JS-based RN SDK, and LaunchDarkly will look into supporting Expo in a better capacity then (when the installation of the LaunchDarkly RN SDK becomes simpler).

**Comment by ridafkih** [comment]
## Expo Go

Expo Go is downloaded from the app store, and allows you to run Expo applications on servers or local machines by scanning the QR code, or typing the "update URL" into the Expo Go application. Since the Expo Go application is a pre-built binary, it comes pre-loaded with certain native dependencies, configurations, etc.

This means that if you want to make native customizations with Expo Go like installing the native Pods required for this library, **simply cannot**. If you are stuck using Expo Go, **find another solution.**

## Expo Development Build

Expo has changed a lot in the past few years, and by pairing an Expo Managed Workflow with a development build, it allows you to build what is essentially your own version of the Expo Go application featuring all the customized native code, files, dependencies, and configurations your heart desires!

One of the build steps for your development build is to install Pods. This is automatically done in the managed workflow with the development build. This means as long <strong>as you have this package installed in a managed workflow with the development build, you're good to go.</strong>

## Get Started with Managed Workflow & Development Build

If you want to get started with the managed workflow and development builds, here is information from the Expo documentation. By using this pairing, you can begin using LaunchDarkly in your Expo application.

[Expo Workflow Types](https://docs.expo.dev/archive/managed-vs-bare/#managed-workflow)
[Development Build Introduction](https://docs.expo.dev/develop/development-builds/introduction/)

**Comment by GabrielDierks** [comment]
Hey everyone just a heads up we managed to implement Launchdarkly successfully with Expo. Essentially there were no extra steps needed for our product that is using a Development build via `prebuild`. The only fix we had to do was to move the "expo-dev-client" package to the devDependencies because otherwise requests wouldn't go through for android!

**Comment by rgommezz** [comment]
I am still struggling with Android, see https://github.com/launchdarkly/react-native-client-sdk/issues/227#issuecomment-1806241075

**Comment by louis-launchdarkly** [comment]
We have taken the request in mind for the development of the next LaunchDarkly React Native SDK - https://github.com/launchdarkly/js-core/tree/main/packages/sdk/react-native is currently in alpha, written in pure JavaScript, and supports Expo 49/RN 0.72.x. If you are interested, we would love to get some feedback before moving this 10.x SDK to GA.

Because the 10.x written in pure JavaScript, which should remove the need to have Expo Config Plugin. Please let us know if there are other reasons that this plugin will still be desirable in the next version.

**Comment by leggomuhgreggo** [comment]
Would this support web?

**Comment by yusinto** [comment]
The react-native SDK has been re-written and [released](https://github.com/launchdarkly/js-core/tree/main/packages/sdk/react-native). The new version v10 is purely in TypeScript and supports Expo. At this time we support iOS and Android only.

Please consider upgrading to that new version to fix this issue. Thank you for your patience.
