### ISSUE TITLE
Version 67 support

### ISSUE THREAD

**Issue by EdwardDrapkin** [launchdarkly/react-native-client-sdk#113]
When can this be expected?

I'm trying to roll out a feature-flag MVP for my company.  We're looking at a 6/7 digit expenditure based on our MAUs.  Should we expect that supported versions of react-native are always going to be a year out of date and rife with security issues?  Should I just abandon this MVP and switch to a platform that cares about react-native?

**Comment by wojteg1337** [comment]
Hey, 

I'm facing same issues.. as a temp solution you could use v4.2.2 which works fine on RN 67.2 (at least iOS, didn't test android yet).

**Comment by Titozzz** [comment]
This libs works fine under 0.67, if you can ignore the android warnings about event emitter

**Comment by louis-launchdarkly** [comment]
Hello @EdwardDrapkin,

We hear your concerns clearly about the state of our React-Native support, given the last few React Native SDK releases (the last patch a few weeks ago, the last minor was about five months ago) have not yet expanded full support for the RN 0.65+. Because the internal development happens on a private mirror that is not visible in this public repository, there is also not a lot of visible action.

Behind the scene, our engineer had been busy working through various issues and we are almost ready to release the SDK changes to add the support to the React Native 0.65, 0.66, and 0.67. We are also improving the test build process we use to make sure going forward, we will not fall as behind on React Native as this time.

The next version will be a major release, given the change in the minimum support version. I will post a new comment on this issue when the new release is public.

Thank you for your interest in using LaunchDarkly.
Louis

And @wojteg1337, @Titozzz, thank you so much for offering a temporary solution and being helpful!

**Comment by louis-launchdarkly** [comment]
Hello @EdwardDrapkin, @wojteg1337, @Titozzz,
Thank you for waiting. We have released the React Native Client SDK 6.0 today, which contains support for RN 0.65, 0.66, and 0.67. Because this version dropped support for RN 0.63, this is a major version release. Please look at the Changelog for more information.

This version also contains changes to the difficult-to-maintain CI process we used before. While this has no visible impact on the SDK logic itself, this enables us to validate the SDK across multiple React Native and XCode releases much more effectively. With this, there will be fewer issues when we need to support new RN versions going forward, and you can expect a more prompt update from us.

The release tag is 
https://github.com/launchdarkly/react-native-client-sdk/releases/tag/6.0.0

**Comment by Titozzz** [comment]
@louis-launchdarkly can you review https://github.com/launchdarkly/react-native-client-sdk/issues/116 please, would be nice to have 6.0.1 soon :)
