### ISSUE TITLE
bug initializing in Android: LDClient.get() was called before init()!

### ISSUE THREAD

**Issue by rtmruczek** [launchdarkly/react-native-client-sdk#120]
**Describe the bug**
Sometimes the `LDClient` fails to initialize on android, and feature flags cannot be retrieved.

**To reproduce**
Appears to be a race condition when configuring the `LDClient`.

**Expected behavior**
The client should initialize consistently.

**Logs**
No helpful logs other than the exception: `LDClient.get() was called before init()!`

**SDK version**
`launchdarkly-react-native-client-sdk@6.1.0`

**Language version, developer tools**
XCode Version 13.2.1 (13C100)

**OS/platform**
Pixel 4a, Android 12

**Additional context**
Noticed that this issue exists, it may be related: https://github.com/launchdarkly/react-native-client-sdk/issues/79

**Comment by louis-launchdarkly** [comment]
Hello @rtmruczek, thank you for reaching out. Similar to the issue you linked, is your initialization code wrapped in `await` like https://github.com/launchdarkly/hello-react-native/blob/master/App.js#L55 ?

If you are already wrapping the initialization with await (or the `isInitialized()` check), and you still see the issue, because we will need to ask you about the initialization code and potentially your configuration, can you reach out through our Support?

**Comment by louis-launchdarkly** [comment]
No response on this issue. Closing this - if the issue is not solved for you, please reach through LaunchDarkly's Support.
