### ISSUE TITLE
"LaunchDarkly SDK already initialized" before configure has been called

### ISSUE THREAD

**Issue by johnnywang** [launchdarkly/react-native-client-sdk#121]
**Describe the bug**
I actually have an open support ticket around this, but hoping this is a bit faster, or, at the very least, allows others encountering the same problem to get some visibility. I've been trying to integrate LD into our RN app, but have been blocked from doing so because the SDK keeps throwing an error saying that the SDK has already been initialized once before, when it has not, following the setup directions here: https://docs.launchdarkly.com/sdk/client-side/react/react-native

Thinking it might be some weird setup with our app, I've even tested this against a vanilla RN app, and continue to see this error.

**To reproduce**

1. Create a new app using: `npx react-native init LDTest`
2. Add LD: `yarn add launchdarkly-react-native-client-sdk`
3. Do whatever else is needed to get that up and running (right Ruby version, install bundler, install pods, etc)
4. Add the following to the beginning of `App.js`
```
const App: () => Node = () => {
  let client = new LDClient();
  client.isInitialized().then((isInitialized) => {
    console.log('initialized? ', isInitialized);
    if (!isInitialized) {
      client
        .configure(
          {mobileKey: '<insert_key>'},
          {key: 'user_key'},
        )
        .then(() => console.log('success'));
    }
  });
```
5. Observe how `initialize?` is only ever logged once, and with `true`

**Expected behavior**
The SDK should not err out before `configure` has been called

**Logs**
![Screen Shot 2022-03-09 at 16 31 59](https://user-images.githubusercontent.com/938210/157566079-5683b622-90f6-4bed-a6c4-4477248c81f3.png)

**SDK version**
```
  "dependencies": {
    "launchdarkly-react-native-client-sdk": "^6.1.0",
    "react": "17.0.2",
    "react-native": "0.67.3"
  },
```

**Language version, developer tools**
React Native, Flipper, yarn

**OS/platform**
MacOS 12.1

**Comment by johnnywang** [comment]
As a workaround, we've resorted to calling `client.close()` immediately after it's been instantiated, as `configure` appears to reopen and restart the stream, i.e.

```
let client = new LDClient();
client.close().then(() => {
  client.configure(...)
```

but it's not clear if there will be unintended consequences as a result of this (as the docs seem to suggest)

**Comment by louis-launchdarkly** [comment]
Hello @johnnywang, thank you for reaching out. I think you can skill the `isInitialized()` check right after `new LDClient()` because the Client is not useful until you have set the Mobile SDK key via `configure`. Also, have you tried to use `await` for the `configure` method call? We have an example here https://github.com/launchdarkly/hello-react-native/blob/master/App.js#L55

Also, as far as we can tell, there is an inconsistency that calling `isInitialized()` before `configure` could just return true for iOS. We will need to look into that more.

**Comment by johnnywang** [comment]
Bumping this thread again: we have a workaround as mentioned above, but it'd still be nice to have this fixed since we don't know if there will be any issues with our workaround

**Comment by louis-launchdarkly** [comment]
Hello @johnnywang, sorry about the late response, in terms of the test app, we are in the process of updating the hello repo, so in the meantime please use the ManualTestApp that comes with this Repo https://github.com/launchdarkly/react-native-client-sdk/tree/6.1.2/ManualTestApp

While I will need to debug more as there is something weird when evaluating an Integer flag, if you follow the instruction, having the iOS Simulator up, the test app should run and can evaluate boolean flags correctly, allowing you to test the initialization code. And the [App.js](https://github.com/launchdarkly/react-native-client-sdk/blob/6.1.2/ManualTestApp/App.js) in the ManualTestApp directory could give you an example of how to initialize the client, as I was not able to see the "LaunchDarkly SDK already initialized" error you reported when I run the test application.

**Comment by louis-launchdarkly** [comment]
And sorry for not mentioning this earlier while we test the behavior you reported.

If it is about using SDK, even when there is behavior that looks like a code bug, we would encourage you to reach out through LaunchDarkly Support, as LaunchDarkly Support helps out a lot of LaunchDarkly customers who set up the SDKs and likely can provide faster responses and suggestions.

**Comment by louis-launchdarkly** [comment]
Hello @shaddeen, just to check, does that happen in all versions of the React Native SDK? Also, have you tried a similar initialization that is in the App.js, using the `async/await` keyword? Because without `await` waiting for the promise to complete, the code could keep proceeding and that could be a reason why this is happening.

**Comment by johnnywang** [comment]
@louis-launchdarkly tried the ManualTestApp, which runs, but still seeing the exact same error, so I'm not sure how this isn't showing up for you

![Screen Shot 2022-04-06 at 20 21 54](https://user-images.githubusercontent.com/938210/162113877-2a84858b-186b-4204-a761-b9cee9c50f02.png)

**Comment by louis-launchdarkly** [comment]
Hello @johnnywang, looking at your log output, are you doing some sort of hot reloading? It seems that at 20:14:14 you didn't get the error, and at 20:21:43 you get it when the app reloads, is that correct?

**Comment by johnnywang** [comment]
@louis-launchdarkly ahh, that makes sense! This is just the hot reload that comes with Metro/RN by default. If I have the app closed entirely and do a cold open, I do see that no error comes up, but that it does show up if I hit R in Metro/the app to reload

**Comment by louis-launchdarkly** [comment]
Hello @johnnywang, you are welcome, and we are looking to provide more documentation around this area going forward because the RN SDK's use of the native adapter to the Android and iOS SDK means the hot reload unfortunately doesn't work (because the reload would not reload the native side of things, just wiping the state from the React side).

If you have any other questions, please feel free to reach out to us. I recommend going through the LaunchDarkly Support ticket system, as the Support Engineers work with a lot of LaunchDarkly customers, and often have the correct answer for you quicker.
