### ISSUE TITLE
Error on build related to swift compiler version

### ISSUE THREAD

**Issue by Deadarius** [launchdarkly/react-native-client-sdk#63]
**Describe the bug**
Following error occurs on build:
```
Module compiled with Swift 5.3 cannot be imported by the Swift 5.3.1 compiler: /Users/xyz/Library/Developer/Xcode/DerivedData/conqasiteapp-abffynglrkfpmcfouodvfxjmzynn/Build/Products/Debug-iphonesimulator/LaunchDarkly/LaunchDarkly.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
```

**To reproduce**
- `npm i launchdarkly-react-native-client-sdk@3.2.2 --save`
- `npx react-native run-ios`

**Expected behavior**
Successfully built and launched on iOS simulator

**Logs**
If applicable, add any log output related to your problem.

**SDK version**
3.2.2

**Language version, developer tools**
- xcode: version 12.2 (12B45b)
- react native: 0.61.0

**OS/platform**
iPhone 11 simulator

**Comment by gwhelanLD** [comment]
Hi @Deadarius,

This error indicates that there's a version mismatch between swift binaries in your project. Since the SDK is only distributed in source form, your system is building the SDK along with your project using whatever version of the swift tooling that is available. The build system is unaware of updates to the swift tooling version so does not trigger a full rebuild automatically after an update, this can cause these sorts of errors as the built binaries have not all been built by the same version anymore. Could you try to do a full clean and rebuild of your project and verify whether your build is fixed?

Thanks,
@gwhelanLD

**Comment by Deadarius** [comment]
@gwhelanLD yup, I tried that, it didn't help :(

**Comment by gwhelanLD** [comment]
I've also seen some issue saying this can be related to the command line tools version you have configured in XCode. Could you try all the steps outlined here, if you haven't already?

https://github.com/lottie-react-native/lottie-react-native/issues/683#issuecomment-694903652 

If that doesn't solve your issue, could you provide build logs here, or to our [support team](https://support.launchdarkly.com/hc/en-us) so we can investigate further?

Thanks

**Comment by Deadarius** [comment]
@gwhelanLD that actually worked, thanks a lot!
