### ISSUE TITLE
Xcode 12 Support

### ISSUE THREAD

**Issue by harika-sabbella** [launchdarkly/react-native-client-sdk#64]
**Is this a support request?**
Given the words from Apple Store: Starting April 2021, all iOS and iPadOS apps submitted to the App Store must be built with Xcode 12 and the iOS 14 SDK.

**Describe the solution you'd like** 
Do you plan to release an SDK before the April 2021 deadline?

**Comment by bwoskow-ld** [comment]
Hi @harika-sabbella ,

Apologies for not yet updating our React Native SDK to support Xcode 12 and iOS 14. We have this work scheduled on our immediate roadmap, along with other improvements and fixes which will be made available by updating our SDK to newer versions of our iOS and Android LaunchDarkly SDK native modules. We should have a release for you in March. Stay tuned.

**Comment by fnando** [comment]
Any updates on this? This issue is really becoming a blocker.

**Comment by bwoskow-ld** [comment]
We're actively working on this and will have a release before the end of the month. We'll update this GitHub issue when a release is available.

**Comment by Chrischuck** [comment]
@bwoskow-ld Can I assume this will be fixed in the next version, just want to be sure this error I'm getting is the same as everyone else:
<img width="1011" alt="Screen Shot 2021-03-25 at 11 51 17 AM" src="https://user-images.githubusercontent.com/13311268/112527781-a59f7600-8d60-11eb-86ea-0ca07e58871f.png">

And will the new version support react native 0.64?

**Comment by bwoskow-ld** [comment]
@Chrischuck Can you confirm what XCode version you're running? Note that the code in your screenshot is from version 4.5.0 of our iOS SDK (bundled as a native module), and the new React Native SDK version we're finishing up bundles a newer iOS SDK version which is compatible with XCode 12 and in which this code is moved/changed.

As for React Native 0.64, we will be adding compatibility with it in the subsequent SDK version. We want to do these separately such that SDK consumers aren't locked in to updating to RN 0.64 in order to gain XCode 12 support.

**Comment by Chrischuck** [comment]
@bwoskow-ld Thanks for response, I'm running Version 12.4 of XCode. Will the update for React Native 0.64 come soon after the release for xcode 12 support? Or do you expect there to be some delay in between

**Comment by bwoskow-ld** [comment]
It'll come soon after.

**Comment by torchhound** [comment]
Xcode 12 support has been added in React Native 4.0.

**Comment by anujraghuvanshi** [comment]
React Native `4.0` 😄   Really 😜 

Jokes Apart. I reached here while finding the solution to my issue. 

I am using XCode v11.5. And trying to run with React native project with version `0.64.1`, but it's not running anyway. 
Is it something like XCode 12 is required to run 0.64.x?

**Comment by bwoskow-ld** [comment]
Hi @anujraghuvanshi,

We meant that Xcode 12 support was added in version 4.0 of our React Native _SDK_. As long as you're on a 4.x version of this SDK you'll have Xcode 12 compatibility.

As for identifying which SDK version to use for your particular version of React Native, please refer to [our readme](https://github.com/launchdarkly/react-native-client-sdk#supported-versions).

Version 4.0 of the SDK should be compatible back to Xcode 11.5 however per Apple's requirements you'll need to upgrade to Xcode 12 because otherwise you won't be able to submit to their App Store.

Cheers,
@bwoskow-ld
