### ISSUE TITLE
Cant initialize client

### ISSUE THREAD

**Issue by Chrischuck** [launchdarkly/react-native-client-sdk#72]
Simply doing the follow breaks (ios and android):
```
 client = new LDClient();
```
resulting error:
<img width="671" alt="Screen Shot 2021-04-14 at 12 47 42 PM" src="https://user-images.githubusercontent.com/13311268/114769929-b28c0580-9d1f-11eb-9bde-2d56ed10682a.png">

react-native-client-sdk version: `4.1.0`
React native version: `0.64`
xcode version: `12.4`

`NativeModules` is an empty object for me [here](https://github.com/launchdarkly/react-native-client-sdk/blob/master/index.js#L1)

**Comment by bwoskow-ld** [comment]
Hi @Chrischuck,

We haven't seen this problem locally while developing or testing the SDK. I have a few diagnostic questions for you:

1. Did you have this problem prior to updating to SDK version `4.1.0`?
2. Can you reproduce the problem when building and running our [sample application](http://github.com/launchdarkly/hello-react-native)?
3. As a sanity check can you verify that you ran `npm install` after updating the SDK package version?

I found [other reports](https://github.com/facebook/react-native/issues/26813) of this issue but there isn't a clear solution there for a potential change in the SDK.

Cheers,
@bwoskow-ld

**Comment by torchhound** [comment]
Hi @Chrischuck, are you running `client.configure()` after you initialize the `LDClient` object?

**Comment by Chrischuck** [comment]
@bwoskow-ld

I didn't have this issue prior to `4.1.0`, android worked fine, but ios did not (since xcode 12). Unfortunately, we're just setting up LD for our app, so we've never had a fully working/deployed solution yet.

I haven't tried the sample app, will give that a shot.

And after bumping versions, I wiped `node_modules`, cleared cache, and reinstalled (we're using yarn if that makes a difference).

@torchhound I am, I'm running `await client.configure(clientConfig, userConfig);` but it fails before it even gets there

**Comment by Chrischuck** [comment]
Still getting the issue with the sample app:
<img width="931" alt="Screen Shot 2021-04-14 at 2 01 18 PM" src="https://user-images.githubusercontent.com/13311268/114778655-fbe15280-9d29-11eb-97a8-0cd5d57dc841.png">

**Comment by bwoskow-ld** [comment]
Hi @Chrischuck ,

We tried to reproduce the error with our sample application on a fresh computer / clone but were unable to do so. At this point we think the problem is related to your environment and/or the steps your taking when building  and running your application. To diagnose the problem further we'd like you to get in touch with our support team. With our support team you'll be able to communicate in a more secure fashion than this publicly-accessible ticket provides. Please email support@launchdarkly.com to get started. You should include a link to this GitHub issue so that they'll see our existing conversation. If the support team needs additional help from our engineering team, they'll escalate to us internally.

Cheers,
@bwoskow-ld
