### ISSUE TITLE
isOffline returns opposite value on iOS

### ISSUE THREAD

**Issue by TheAlmightyBob** [launchdarkly/react-native-client-sdk#99]
**Describe the bug**
The `isOffline` API returns `true` on iOS if the SDK is _online_, and `false` if it is _offline_.
This is a regression between 4.1.2 and 4.2.0, as [this change](https://github.com/launchdarkly/react-native-client-sdk/compare/4.1.2...4.2.0#diff-cd97361c4f9361640dd6bed725225b77187ed86a1465713e326390be4ed932b6L449) flipped the return value.

**To reproduce**
Call `LDClient.configure` with a configuration that explicitly sets `offline` to `true` or `false`. Then call `LDClient.isOffline`. It will return the opposite of whatever you had set.

**Expected behavior**
`isOffline` returns `true` if in offline mode and `false` if in online mode.

**SDK version**
4.2.0 - 4.2.2
I haven't yet tackled the 4->5 migration, however I looked through code diffs for both this repo and the iOS SDK repo and didn't see any changes related to offline mode, so I _expect_ this is still an issue.

**OS/platform**
iOS (I've also tested Android and verified that it does _not_ have this issue)

**Comment by gwhelanLD** [comment]
Hi @TheAlmightyBob,

Thanks for reporting this issue! I'm not sure how that change slipped through. The value is expected to be inverted in the iOS wrapper because the iOS SDK provides `isOnline` rather than `isOffline` like RN/Android does. It does appear that this issue exists in the 5.x SDK releases. I've filed an internal ticket to address this.

Thanks!
@gwhelanLD

**Comment by gwhelanLD** [comment]
Hi @TheAlmightyBob,

This has been resolved in the [5.1.1 release](https://github.com/launchdarkly/react-native-client-sdk/releases/tag/5.1.1), thank you for the report!

Thanks,
@gwhelanLD
